DROP TABLE IF EXISTS AUTHOR CASCADE;
CREATE TABLE AUTHOR(
        ID BIGSERIAL,
        NAME VARCHAR(255) UNIQUE,
        PRIMARY KEY(ID));

DROP TABLE IF EXISTS GENRE CASCADE;
CREATE TABLE GENRE(
        ID BIGSERIAL PRIMARY KEY,
        NAME VARCHAR(255) UNIQUE);


DROP TABLE IF EXISTS BOOK CASCADE;
CREATE TABLE BOOK(
        ID BIGSERIAL PRIMARY KEY,
        NAME VARCHAR(255) UNIQUE,
        AUTHORID BIGINT REFERENCES AUTHOR(ID),
        GENREID BIGINT REFERENCES GENRE(ID));

DROP TABLE IF EXISTS COMMENT CASCADE;
CREATE TABLE COMMENT(
        ID BIGSERIAL,
        COMMENT VARCHAR(255),
        BOOKID BIGINT REFERENCES BOOK(ID),
        PRIMARY KEY(ID));
