version: '3'

services:
  postgres:
    image: "postgres"
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    stdin_open: true
    ports:
      - 5432:5432
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    stdin_open: true
#    tty: true
#    ports:
#      - 8080:8080
#    environment:
#      - DB_DRIVER=org.postgresql.Driver
#      - DB_URL=jdbc:postgresql://postgres:5432/db
#      - DB_USERNAME=postgres
#      - DB_PASSWORD=pass
#      - WAIT_FOR=postgres:5432
