DROP TABLE IF EXISTS FROG;
CREATE TABLE FROG(
        ID BIGSERIAL PRIMARY KEY,
        NAME VARCHAR(255) UNIQUE,
        STATE VARCHAR(255));


DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
        ID BIGSERIAL,
        USERNAME VARCHAR(255),
        PASSWORD VARCHAR(255),
        ROLE VARCHAR(255),
        PRIMARY KEY(ID));
