DROP TABLE IF EXISTS LIM_CURRENCY;
CREATE TABLE LIM_CURRENCY(
        ID BIGSERIAL,
        NAME VARCHAR(255) UNIQUE,
        ISO_CODE VARCHAR(255) UNIQUE,
        ALPHA_CODE VARCHAR(255) UNIQUE,
        PRIMARY KEY(ID));

DROP TABLE IF EXISTS LIM_LIMIT;
CREATE TABLE LIM_LIMIT(
        ID BIGSERIAL PRIMARY KEY,
        NAME VARCHAR(255) UNIQUE,
        COMMENT VARCHAR(255),
        STARTDATE DATE,
        ENDDATE DATE,
        VALUE NUMERIC(38,10),
        CURRENCYID BIGINT REFERENCES LIM_CURRENCY(ID));

DROP TABLE IF EXISTS LIM_LimitCondition;
CREATE TABLE LIM_LimitCondition(
        ID BIGSERIAL,
        CONDITIONKIND INTEGER,
        CONDITIONVALUE  NUMERIC(19, 0),
        LIMITID BIGINT REFERENCES LIM_LIMIT(ID),
        PRIMARY KEY(ID));

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
        ID BIGSERIAL,
        USERNAME VARCHAR(255),
        PASSWORD VARCHAR(255),
        ROLE VARCHAR(255),
        PRIMARY KEY(ID));