spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  data:
    mongodb:
      database: libraryMongo

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false

logging:
  level:
    ROOT: ERROR

#org:
#  hibernate:
#    SQL: DEBUG
#    type: TRACE