DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
        ID BIGSERIAL,
        NAME VARCHAR(255) UNIQUE,
        PRIMARY KEY(ID));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(
        ID BIGSERIAL PRIMARY KEY,
        NAME VARCHAR(255) UNIQUE);


DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
        ID BIGSERIAL PRIMARY KEY,
        NAME VARCHAR(255) UNIQUE,
        AUTHORID BIGINT REFERENCES AUTHOR(ID),
        GENREID BIGINT REFERENCES GENRE(ID));

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT(
        ID BIGSERIAL,
        COMMENT VARCHAR(255),
        BOOKID BIGINT REFERENCES BOOK(ID),
        PRIMARY KEY(ID));

